variables:
  GIT_STRATEGY: clone
  MAVEN_CLI_OPTS: "clean"
  
stages: 
  - build
  - test
  - test_deploy
  - master_deploy
  
build: 
  stage: build
  tags: 
    - ugrad
  script: 
    - cd ./Chess  
    - mvn $MAVEN_CLI_OPTS compile

test: 
  stage: test
  tags: 
    - ugrad
  script: 
    - cd ./Chess
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit:
        - ./Chess/target/surefire-reports/TEST-*.xml
        
test_deploy:
  stage: test_deploy
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:2.6
  script:
    - cd ./Chess
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop

master_deploy:
  stage: master_deploy
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:2.6
  script:
    - cd ./Chess
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP_NAME --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - master