stages: 
  - build
  - test
  
build: 
  stage: build
  tags: 
    - ugrad
  script: 
    - cd ./Chess  
    - mvn compile

test: 
  stage: test
  tags: 
    - ugrad
  script: 
    - cd ./Chess
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit:
        - ./Chess/target/surefire-reports/TEST-*.xml
