variables:
  GIT_STRATEGY: clone
  MAVEN_CLI_OPTS: "clean"
  HEROKU_APP_NAME: "chess5308"
  HEROKU_API_KEY: "fb93c56f-e5e2-46af-9910-d2635f1359de"
  
stages: 
  - build
  - test
  - deploy
  
build: 
  stage: build
  tags: 
    - ugrad
  script: 
    - cd ./Chess  
    - mvn $MAVEN_CLI_OPTS compile

test: 
  stage: test
  tags: 
    - ugrad
  script: 
    - cd ./Chess
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit:
        - ./Chess/target/surefire-reports/TEST-*.xml
        
deploy:
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:2.6
  script:
    - cd ./Chess
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop
